---
- hosts: local
  connection: local
  gather_facts: False
  tasks:
  - name: Create the host security group
    ec2_group:
      name: Ansible Security Group
      description: Security Group for new host
      region: ap-southeast-2
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: basic_firewall

  - name: Launch the new EC2 Instance
    ec2:
      group: Ansible Security Group
      instance_type: t2.micro
      image: ami-423bec20
      wait: true 
      region: ap-southeast-2
      keypair: ansible-answers-key
      count: 1
    register: ec2

  - name: Add the name of the server to the hosts file
    lineinfile:
      dest: "./hosts"
      regexp: '{{ item.public_ip }}'
      insertafter: "[splunkserver]"
      line: '{{ item.public_ip }}'
    with_items: '{{ ec2.instances }}'

  - name: Wait for SSH to come up
    wait_for:
      host: '{{ item.public_ip }}'
      port: 22 
      state: started
    with_items: '{{ ec2.instances }}'

  - name: Add tag to Instance(s)
    ec2_tag:
      resource: '{{ item.id }}'
      region: ap-southeast-2
      state: present
    with_items: '{{ ec2.instances }}'
    args:
      tags:
        Name: splunkserver
